### ISSUE TITLE
some of the oplog tailers never stop

### ISSUE THREAD

**Issue by islue** [Percona-Lab/mongodb_consistent_backup#165]
Here is a piece of logs. No warn or error captured.
```
[2017-06-03 16:42:55,634] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 176740 oplog changes, ts: Timestamp(1496508174, 25)
[2017-06-03 16:43:01,184] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1123373 oplog changes, ts: Timestamp(1496508180, 48)
[2017-06-03 16:43:26,595] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 178661 oplog changes, ts: Timestamp(1496508205, 35)
[2017-06-03 16:43:32,116] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1134272 oplog changes, ts: Timestamp(1496508211, 64)
[2017-06-03 16:43:56,693] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 180553 oplog changes, ts: Timestamp(1496508235, 46)
[2017-06-03 16:44:02,942] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1144761 oplog changes, ts: Timestamp(1496508241, 310)
[2017-06-03 16:44:26,900] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 182454 oplog changes, ts: Timestamp(1496508265, 56)
[2017-06-03 16:44:33,736] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1155331 oplog changes, ts: Timestamp(1496508272, 217)
[2017-06-03 16:44:56,900] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 184355 oplog changes, ts: Timestamp(1496508296, 15)
[2017-06-03 16:45:04,596] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1165687 oplog changes, ts: Timestamp(1496508303, 219)
[2017-06-03 16:45:27,104] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 186225 oplog changes, ts: Timestamp(1496508326, 8)
[2017-06-03 16:45:35,380] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1175690 oplog changes, ts: Timestamp(1496508334, 143)
[2017-06-03 16:45:57,339] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 188117 oplog changes, ts: Timestamp(1496508356, 30)
[2017-06-03 16:46:06,226] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1185682 oplog changes, ts: Timestamp(1496508365, 125)
[2017-06-03 16:46:27,434] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 189992 oplog changes, ts: Timestamp(1496508386, 35)
[2017-06-03 16:46:37,111] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1196267 oplog changes, ts: Timestamp(1496508396, 34)
[2017-06-03 16:46:57,555] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 191871 oplog changes, ts: Timestamp(1496508416, 43)
[2017-06-03 16:47:07,986] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1206821 oplog changes, ts: Timestamp(1496508427, 1)
[2017-06-03 16:47:27,650] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 193755 oplog changes, ts: Timestamp(1496508446, 57)
[2017-06-03 16:47:38,744] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1217278 oplog changes, ts: Timestamp(1496508457, 294)
[2017-06-03 16:47:57,678] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 195634 oplog changes, ts: Timestamp(1496508476, 52)
[2017-06-03 16:48:09,573] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1228031 oplog changes, ts: Timestamp(1496508488, 220)
[2017-06-03 16:48:27,820] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 197515 oplog changes, ts: Timestamp(1496508506, 64)
[2017-06-03 16:48:40,427] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1237997 oplog changes, ts: Timestamp(1496508519, 123)
[2017-06-03 16:48:43,486] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] ps-rs1/ip-10-1-15-43:27017:      [####....................]  .oplog  196708/1017579  (19.3%)
[2017-06-03 16:48:46,486] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] ps-rs1/ip-10-1-15-43:27017:      [###############.........]  .oplog  640370/1017579  (62.9%)
[2017-06-03 16:48:49,486] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] ps-rs1/ip-10-1-15-43:27017:      [########################]  .oplog  1065050/1017579  (104.7%)
[2017-06-03 16:48:50,471] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] ps-rs1/ip-10-1-15-43:27017:      [########################]  .oplog  1180521/1017579  (116.0%)
[2017-06-03 16:48:58,662] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 199453 oplog changes, ts: Timestamp(1496508537, 48)
[2017-06-03 16:49:00,705] [INFO] [MongodumpThread-5] [MongodumpThread:run:161] Backup ps-rs1/ip-10-1-15-43:27017 completed in 2936.25 seconds, 1180521 oplog changes, end ts: Timestamp(1496508522, 35)
[2017-06-03 16:49:11,341] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1248646 oplog changes, ts: Timestamp(1496508550, 148)
[2017-06-03 16:49:28,739] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 201349 oplog changes, ts: Timestamp(1496508567, 59)
[2017-06-03 16:49:42,211] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1259175 oplog changes, ts: Timestamp(1496508581, 35)
[2017-06-03 16:49:59,717] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 203345 oplog changes, ts: Timestamp(1496508598, 90)
[2017-06-03 16:50:13,149] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1269164 oplog changes, ts: Timestamp(1496508612, 50)
[2017-06-03 16:50:29,805] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 205246 oplog changes, ts: Timestamp(1496508628, 96)
[2017-06-03 16:50:43,957] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1279387 oplog changes, ts: Timestamp(1496508642, 309)
[2017-06-03 16:50:55,486] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] ps-rs0/ip-10-1-15-239:27017:     [#######.................]  .oplog  361056/1120609  (32.2%)
[2017-06-03 16:50:58,486] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] ps-rs0/ip-10-1-15-239:27017:     [#################.......]  .oplog  797852/1120609  (71.2%)
[2017-06-03 16:50:59,961] [INFO] [TailThread-4] [TailThread:status:61] Oplog tailer ps-rsc/ip-10-1-12-46:27019 status: 207130 oplog changes, ts: Timestamp(1496508658, 109)
[2017-06-03 16:51:01,486] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] ps-rs0/ip-10-1-15-239:27017:     [########################]  .oplog  1174436/1120609  (104.8%)
[2017-06-03 16:51:02,356] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] ps-rs0/ip-10-1-15-239:27017:     [########################]  .oplog  1281210/1120609  (114.3%)
[2017-06-03 16:51:13,938] [INFO] [MongodumpThread-6] [MongodumpThread:run:161] Backup ps-rs0/ip-10-1-15-239:27017 completed in 3069.48 seconds, 1281210 oplog changes, end ts: Timestamp(1496508652, 197)
[2017-06-03 16:51:14,722] [INFO] [TailThread-3] [TailThread:status:61] Oplog tailer ps-rs0/ip-10-1-15-239:27017 status: 1289044 oplog changes, ts: Timestamp(1496508673, 255)
[2017-06-03 16:51:17,912] [INFO] [MainProcess] [Mongodump:wait:92] All mongodump backups completed successfully
[2017-06-03 16:51:17,913] [INFO] [MainProcess] [Stage:run:92] Completed running stage mongodb_consistent_backup.Backup with task Mongodump in 3073.48 seconds
[2017-06-03 16:51:17,914] [INFO] [MainProcess] [Tailer:stop:72] Stopping all oplog tailers
[2017-06-03 16:51:17,942] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:18,443] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:18,944] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:19,446] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:19,947] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:20,448] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:20,949] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:21,450] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:21,952] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:22,453] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:22,954] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:23,455] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:23,956] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:24,457] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:24,959] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:25,460] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:25,961] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:26,462] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:26,963] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:27,464] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:27,966] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:28,467] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:28,968] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:29,469] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:29,970] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
[2017-06-03 16:51:30,472] [INFO] [MainProcess] [Tailer:stop:94] Waiting for ps-rs1/ip-10-1-15-43:27017 tailer to reach ts: Timestamp(1496508677, 234), currrent: Timestamp(1496506248, 198)
```

**Comment by timvaillancourt** [comment]
Hi @islue, I've been working on a fix for this same issue. This will be in the 1.0.4 release.

I will be moving the 'last_ts' stop position (that the threads wait for) to a multiprocessing.Pipe because using a multiprocessing.Manager.dict() field at high volume seems to trigger this issue (although I couldn't explain why aside from the symptom, possible the locking)

**Comment by timvaillancourt** [comment]
Hi @islue,

I believe I have merged a fix for this issue. I'd appreciate if you could test and see if this branch resolves your issue: https://github.com/Percona-Lab/mongodb_consistent_backup/tree/1.0.4.

The major change is support for resuming cursors that timeout and much more exception handling for errors in Oplog/Tailer/TailThread.py.

If this doesn't fix this issue we should at least be much more error output to debug.

**Comment by islue** [comment]
I have updated the binary file and it will be used for the scheduled backup.
The issue does not always occur. For example, it ran successfully twice last week. I'll report here if I get any errors.

**Comment by timvaillancourt** [comment]
Yes, I've noticed the same thing. It does not always happen and this problem only happens on systems that are very busy with updates.

I believe it is related to either how busy the host running the backup is or the hosts it takes the backups from. It could also be locking in multiprocessing.Manager, etc.

**Comment by islue** [comment]
Hi @timvaillancourt, I'm not sure if it is a relevant issue, but our backup yesterday failed.
````
[2017-06-25 16:06:03,746] [INFO] [TailThread-3] [TailThread:status:86] Oplog tailer rs1/ip-10-1-16-77:27017 status: 166891 oplog changes, ts: Timestamp(1498406763, 1175)
[2017-06-25 16:06:04,704] [INFO] [TailThread-4] [TailThread:status:86] Oplog tailer rsc/ip-10-1-12-86:27019 status: 1794 oplog changes, ts: Timestamp(1498406764, 1)
[2017-06-25 16:06:06,726] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] rs1/ip-10-1-16-77:27017: [#.......................]            monoceros.receipts  24200666/563549319   (4.3%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] rs0/ip-10-1-16-127:27017:        [#.......................]            monoceros.receipts  27951019/564203530   (5.0%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] rs1/ip-10-1-16-77:27017: [##......................]  monoceros.stats_rtb_with_tag  17935853/195536488   (9.2%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] rs0/ip-10-1-16-127:27017:        [##......................]  monoceros.stats_rtb_with_tag  22031614/197573048  (11.2%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] rs1/ip-10-1-16-77:27017: [##......................]           monoceros.stats_ads  18101417/172772985  (10.5%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] rs0/ip-10-1-16-127:27017:        [#######.................]     monoceros.stats_segmented   16369196/52662299  (31.1%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-6] [MongodumpThread:wait:92] rs1/ip-10-1-16-77:27017: [#######.................]     monoceros.stats_segmented   14776245/50319132  (29.4%)
[2017-06-25 16:06:06,727] [INFO] [MongodumpThread-5] [MongodumpThread:wait:92] rs0/ip-10-1-16-127:27017:        [##......................]           monoceros.stats_ads  16897142/186428943   (9.1%)
[2017-06-25 16:06:08,746] [ERROR] [TailThread-3] [TailThread:run:149] Tailer rs1/ip-10-1-16-77:27017 encountered error: Tailer host changed from (u'ip-10-1-14-32', 27017) to (u'ip-10-1-14-216', 27017)!
Process TailThread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/var/lib/mongodb-consistent-backup/.pex/install/mongodb_consistent_backup-1.0.3-py2-none-any.whl.d8d05091393dd32102eb35126e9e63b115191366/mongodb_consistent_backup-1.0.3-py2-none-any.whl/mongodb_consistent_backup/Oplog/Tailer/TailThread.py", line 152, in run
    raise OperationError(e)
OperationError: Tailer host changed from (u'ip-10-1-14-32', 27017) to (u'ip-10-1-14-216', 27017)!
[2017-06-25 16:06:09,130] [ERROR] [MainProcess] [Mongodump:wait:95] Received backup stop event due to error(s), stopping backup!
[2017-06-25 16:06:09,132] [ERROR] [MainProcess] [Stage:run:95] Stage mongodb_consistent_backup.Backup did not complete!
[2017-06-25 16:06:09,132] [CRITICAL] [MainProcess] [Main:exception:219] Problem performing backup! Error: Stage mongodb_consistent_backup.Backup did not complete!
[2017-06-25 16:06:09,132] [INFO] [MainProcess] [Main:cleanup_and_exit:175] Starting cleanup procedure! Stopping running threads
[2017-06-25 16:06:09,133] [INFO] [MainProcess] [Sharding:restore_balancer_state:141] Restoring balancer state to: True
[2017-06-25 16:06:09,148] [INFO] [MainProcess] [Mongodump:close:189] Stopping all mongodump threads
[2017-06-25 16:06:09,148] [INFO] [MainProcess] [Mongodump:close:197] Stopped all mongodump threads
[2017-06-25 16:06:10,153] [INFO] [MainProcess] [Main:cleanup_and_exit:205] Cleanup complete, exiting
[2017-06-25 16:06:10,154] [INFO] [MainProcess] [Logger:rotate:81] Running rotation of log files
[2017-06-25 16:06:10,154] [INFO] [MainProcess] [Logger:compress:60] Compressing log file: /var/log/mongodb-consistent-backup/backup.stats.20170618_1600.log
````
No server fail was detected.

**Comment by islue** [comment]
Just FYI, it failed for the same reason again.

**Comment by timvaillancourt** [comment]
Thanks @islue, I'll continue to work on this. Unfortunately I'm not sure of the cause just yet.

**Comment by Bastian82** [comment]
We are suffering similair issue, on our clusters. It's happening frequently, everyday on vary clusters. Backups for all clusters launch are on the same time on the server. Below example of logs:

> 017-11-11 05:15:54,754] [INFO] [TailThread-6] [TailThread:status:86] Oplog tailer db_4-rs2/host5103.database5.net:27419 status: 15432 oplog changes, ts: Timestamp(1510372969, 55)
[2017-11-11 05:15:54,754] [INFO] [TailThread-4] [TailThread:status:86] Oplog tailer db_4-rs0/host5327.database5.net:27417 status: 13534 oplog changes, ts: Timestamp(1510373526, 10)
[2017-11-11 05:15:54,754] [INFO] [TailThread-2] [TailThread:status:86] Oplog tailer cfg-rs-db_4/host5512.database5.net:27023 status: 1811 oplog changes, ts: Timestamp(1510373742, 4)
[2017-11-11 05:15:56,602] [INFO] [MongodumpThread-10] [MongodumpThread:wait:130] db_4-rs3/host5104.database5.net:27420:	[##################......]  ppc_budget_svc.campaigns_bac_20171018_0935  293388/374700  (78.3%)
[2017-11-11 05:15:56,786] [ERROR] [TailThread-6] [TailThread:run:151] Tailer db_4-rs2/host5103.database5.net:27419 encountered error: Tailer host changed from ('host5103.database5.net', 27419) to (u's51027.database5.net', 27419)!
[2017-11-11 05:15:56,848] [INFO] [MongodumpThread-11] [MongodumpThread:wait:130] db_4-rs2/host5103.database5.net:27419:	[###################.....]  inv_acc_svc.invoiceAccounts  385545/484692  (79.5%)
[2017-11-11 05:15:57,146] [ERROR] [MainProcess] [Mongodump:wait:90] Received backup stop event due to error(s), stopping backup!
[2017-11-11 05:15:57,147] [ERROR] [MainProcess] [Stage:run:95] Stage mongodb_consistent_backup.Backup did not complete!
[2017-11-11 05:15:57,147] [CRITICAL] [MainProcess] [Main:exception:207] Problem performing backup! Error: Stage mongodb_consistent_backup.Backup did not complete!
[2017-11-11 05:15:57,147] [INFO] [MainProcess] [Main:cleanup_and_exit:163] Starting cleanup procedure! Stopping running threads
[2017-11-11 05:15:57,148] [INFO] [MainProcess] [Sharding:restore_balancer_state:141] Restoring balancer state to: False
[2017-11-11 05:15:57,161] [INFO] [MainProcess] [Mongodump:close:184] Stopping all mongodump threads
[2017-11-11 05:15:57,161] [INFO] [MainProcess] [Mongodump:close:192] Stopped all mongodump threads
[2017-11-11 05:15:58,735] [INFO] [TailThread-5] [TailThread:run:176] Done tailing oplog on db_4-rs3/host5104.database5.net:27420, 9602 oplog changes, end ts: Timestamp(1510373742, 4)
[2017-11-11 05:15:59,670] [INFO] [MainProcess] [Main:cleanup_and_exit:193] Cleanup complete, exiting
[2017-11-11 05:15:59,670] [INFO] [MainProcess] [Logger:rotate:81] Running rotation of log files
[2017-11-11 05:15:59,670] [INFO] [MainProcess] [Logger:compress:60] Compressing log file: /var/log/mongo_backup/backup.db_4.20171110_0500.log

Whats going on here?
>[2017-11-11 05:15:56,786] [ERROR] [TailThread-6] [TailThread:run:151] Tailer db_4-rs2/host5103.database5.net:27419 encountered error: Tailer host changed from ('host5103.database5.net', 27419) to (u's51027.database5.net', 27419)!

**Comment by Bastian82** [comment]
Update:
We hard set number of mongodump threads (--backup.mongodump.threads) as default (dynamic) setting spawn to many bringing very high load to cpu's, but still got the same error, even when cpu load is way below number of cores. What is the progress of this issue? Is there any suggestions how can we avoid those bug ?

**Comment by timvaillancourt** [comment]
@Bastian82 has this same problem:

> We suffering errors described here #165 In log we can read that mongodb-consistent-backup failed and it is stoping mongodump threads:
https://pastebin.com/9vBvVXvG

>but processes is still running and mongodump still dumping data to the backup directories:
https://pastebin.com/e7eLz9vu

**Comment by timvaillancourt** [comment]
Hello @Bastian82 and @islue.

As the operating system, linux kernels, python versions, mongodump versions, OS python modules and many other variables can create a lot of confusion in troubleshooting I'd like to see if this issue can be reproduced on our official Docker container: https://hub.docker.com/r/perconalab/mongodb_consistent_backup/. This will isolate the problem massively.

Could you please test using the 1.2.0 Docker container?

Assuming your config file is in the path: './conf/mcb.conf', it can be started like so:

```
docker run -v ./conf:/conf -v ./data:/var/lib/mongodb-consistent-backup -it perconalab/mongodb_consistent_backup:1.2.0 --config /conf/mcb.conf --verbose
```

The backup data will be outputted to './data' in this example. Please submit verbose log if issue can be reproduced.

**Comment by islue** [comment]
Hello @timvaillancourt 
Our data set grows up to about 3TB and I gave up to backup with mongodump.
So I have no proper env to reproduce the issue, sorry.

**Comment by xChrisPx** [comment]
Hi,
we can reproduce this one quite consistently. With `1.2.0` we get this output:

```
[2018-04-09 17:26:53,496] [DEBUG] [TailThread-6] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/oplog-tailed.bson (secs_since=1.81, changes=6, ts=Timestamp(1523294813, 1))
[2018-04-09 17:26:54,645] [DEBUG] [TailThread-6] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/oplog-tailed.bson (secs_since=1.15, changes=12, ts=Timestamp(1523294814, 7))
[2018-04-09 17:26:54,944] [DEBUG] [TailThread-7] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/cfgRepl/oplog-tailed.bson (secs_since=6.78, changes=13, ts=Timestamp(1523294820, 1))
[2018-04-09 17:26:55,756] [DEBUG] [TailThread-6] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/oplog-tailed.bson (secs_since=1.11, changes=6, ts=Timestamp(1523294815, 1))
[2018-04-09 17:26:55,958] [DEBUG] [TailThread-7] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/cfgRepl/oplog-tailed.bson (secs_since=1.01, changes=27, ts=Timestamp(1523294821, 8))
[2018-04-09 17:26:56,941] [INFO] [TailThread-7] [TailThread:status:87] Oplog tailer cfgRepl/mongoc2.wewear.fashion:7778 status: 6342 oplog changes, ts: Timestamp(1523294822, 1)
[2018-04-09 17:26:56,960] [DEBUG] [TailThread-7] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/cfgRepl/oplog-tailed.bson (secs_since=1.00, changes=16, ts=Timestamp(1523294822, 2))
[2018-04-09 17:26:57,399] [DEBUG] [MongodumpThread-8] [Oplog:open:36] Opening oplog file /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/dump/oplog.bson
[2018-04-09 17:26:57,400] [DEBUG] [MongodumpThread-8] [Oplog:load:53] Reading oplog file /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/dump/oplog.bson
[2018-04-09 17:26:57,548] [INFO] [MongodumpThread-8] [MongodumpThread:run:240] Backup repl1/mongo1.wewear.fashion:27017 completed in 966.13 seconds, 3669 oplog changes, end ts: Timestamp(1523294816, 6)
[2018-04-09 17:26:57,855] [DEBUG] [TailThread-6] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/oplog-tailed.bson (secs_since=2.10, changes=12, ts=Timestamp(1523294817, 1))
[2018-04-09 17:26:58,221] [DEBUG] [TailThread-7] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/cfgRepl/oplog-tailed.bson (secs_since=1.26, changes=7, ts=Timestamp(1523294823, 1))
[2018-04-09 17:26:58,866] [DEBUG] [TailThread-6] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/oplog-tailed.bson (secs_since=1.01, changes=3, ts=Timestamp(1523294818, 1))
[2018-04-09 17:27:00,547] [DEBUG] [TailThread-6] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/repl1/oplog-tailed.bson (secs_since=1.68, changes=3, ts=Timestamp(1523294820, 1))
[2018-04-09 17:27:01,326] [DEBUG] [TailThread-7] [Oplog:autoflush:107] Fsyncing /var/lib/mongodb-consistent-backup/default/20180409_1710/cfgRepl/oplog-tailed.bson (secs_since=3.10, changes=12, ts=Timestamp(1523294826, 1))
[2018-04-09 17:27:01,477] [ERROR] [MainProcess] [Stage:run:99] Stage mongodb_consistent_backup.Backup did not complete!
```

The `Tailer host changed` one sometimes shows up and sometimes it does not.
