### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by nathanderson10** [Percona-Lab/mongodb_consistent_backup#194]
I receive the following error when trying to compile:

Could not satisfy all requirements for multiprocessing:
    multiprocessing
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "~/mongodb_consistent_backup/build/venv/lib/python2.7/site-packages/pex/crawler.py", line 144, in execute
  File "/usr/local/lib/python2.7/Queue.py", line 172, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by timvaillancourt** [comment]
Hi @nathanderson10,

Could you provide:
1) The steps you are using to build the tool.
2) The command you're using to run the tool.
3) The output of "mongodb-consistent-backup --version" and your version of Python.

Thanks!

**Comment by timvaillancourt** [comment]
Hello @nathanderson10, closing this due to no response.

We have a new 1.2.0 release that should be tested in case this is now fixed. If the issue still occurs please create a new issue with the details requested above.
