### ISSUE TITLE
 [ERROR] [MainProcess] [Main:exception:221] Problem starting archiver! Error: 'tar'

### ISSUE THREAD

**Issue by supersujj** [Percona-Lab/mongodb_consistent_backup#215]
what is the problem?
mongodb version:3.4.7
os version  RHEL 7.2

 ./mongodb-consistent-backup -H 127.0.0.1 -P 27022 -u admin -p admin -a admin -n test -l /tmp
[2017-09-08 18:18:28,784] [INFO] [MainProcess] [Main:init:144] Starting mongodb-consistent-backup version 1.1.0 (git commit: GIT_COMMIT_HASH)
[2017-09-08 18:18:28,785] [INFO] [MainProcess] [Main:init:145] Loaded config: {"archive": {"method": "tar"}, "authdb": "admin", "backup": {"location": "/tmp", "method": "mongodump", "mongodump": {"binary": "/usr/bin/mongodump", "compression": "auto"}, "name": "test"}, "environment": "production", "host": "127.0.0.1", "lock_file": "/tmp/mongodb-consistent-backup.lock", "notify": {"method": "none"}, "oplog": {"compression": "none", "flush": {"max_docs": 1000, "max_secs": 1}, "tailer": {"enabled": "true", "status_interval": 30}}, "password": "******", "port": 27022, "replication": {"max_lag_secs": 10, "max_priority": 1000}, "sharding": {"balancer": {"ping_secs": 3, "wait_secs": 300}}, "upload": {"gs": {"threads": 4}, "method": "none", "s3": {"chunk_size_mb": 50, "region": "us-east-1", "retries": 5, "secure": true, "threads": 4}}, "username": "admin"}
[2017-09-08 18:18:28,785] [INFO] [MainProcess] [Stage:init:31] Notify stage disabled, skipping
[2017-09-08 18:18:29,488] [INFO] [MainProcess] [State:init:135] Initializing root state directory /tmp/test
[2017-09-08 18:18:29,489] [INFO] [MainProcess] [State:load_backups:153] Found 0 existing completed backups for set
[2017-09-08 18:18:29,491] [INFO] [MainProcess] [State:init:119] Initializing backup state directory: /tmp/test/20170908_1818
[2017-09-08 18:18:29,495] [ERROR] [MainProcess] [Main:exception:221] Problem starting archiver! Error: 'tar'
Traceback (most recent call last):
  File "/root/.pex/install/mongodb_consistent_backup-1.1.0-py2-none-any.whl.7d5d092f7f7ce18abfa47bf8b118069a47d2f66a/mongodb_consistent_backup-1.1.0-py2-none-any.whl/mongodb_consistent_backup/Main.py", line 251, in run
    self.backup_directory
  File "/root/.pex/install/mongodb_consistent_backup-1.1.0-py2-none-any.whl.7d5d092f7f7ce18abfa47bf8b118069a47d2f66a/mongodb_consistent_backup-1.1.0-py2-none-any.whl/mongodb_consistent_backup/Archive/Archive.py", line 8, in __init__
    self.init()
  File "/root/.pex/install/mongodb_consistent_backup-1.1.0-py2-none-any.whl.7d5d092f7f7ce18abfa47bf8b118069a47d2f66a/mongodb_consistent_backup-1.1.0-py2-none-any.whl/mongodb_consistent_backup/Pipeline/Stage.py", line 45, in init
    **self.args
  File "/root/.pex/install/mongodb_consistent_backup-1.1.0-py2-none-any.whl.7d5d092f7f7ce18abfa47bf8b118069a47d2f66a/mongodb_consistent_backup-1.1.0-py2-none-any.whl/mongodb_consistent_backup/Archive/Tar/Tar.py", line 28, in __init__
    self.compression_method = self.config.archive.tar.compression
  File "/root/.pex/install/yconf-0.3.4-py2-none-any.whl.4c32acf64a3f2408d71fe4642e2daf2f77807381/yconf-0.3.4-py2-none-any.whl/yconf/util.py", line 52, in __getattr__
    raise AttributeError(e)
AttributeError: 'tar'
[2017-09-08 18:18:29,593] [INFO] [MainProcess] [Main:cleanup_and_exit:175] Starting cleanup procedure! Stopping running threads
[2017-09-08 18:18:29,603] [INFO] [MainProcess] [Main:cleanup_and_exit:205] Cleanup complete, exiting

**Comment by timvaillancourt** [comment]
This was repaired yesterday in https://github.com/Percona-Lab/mongodb_consistent_backup/commit/d40d63675e9240c48515b00d2041df6483ce9931.

Please update from the master branch and reopen if this still occurs.
