### ISSUE TITLE
nsca crypto

### ISSUE THREAD

**Issue by jsatterfield** [Percona-Lab/mongodb_consistent_backup#92]
Allow configuration of pynsca crypto mode.
Include python-mcrypt and pycrypto in requirements.txt.
Don't assume mode 16 just because a password is defined.

**Comment by timvaillancourt** [comment]
Thanks @jsatterfield. If I have it right we should assume encryption mode '1' unless '16' (mcrypt) is used, does that sound right?

**Comment by timvaillancourt** [comment]
It appears there is some issues with the PyPi python-mcrypt package, adding it to our requirements causes Pip to error on the build:

```
$ sudo pip -v install python-mcrypt==1.1
Collecting python-mcrypt==1.1
  1 location(s) to search for versions of python-mcrypt:
  * https://pypi.python.org/simple/python-mcrypt/
  Getting page https://pypi.python.org/simple/python-mcrypt/
  Looking up "https://pypi.python.org/simple/python-mcrypt/" in the cache
  Current age based on date: 0
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 0
  Analyzing links from page https://pypi.python.org/simple/python-mcrypt/
  Could not find a version that satisfies the requirement python-mcrypt==1.1 (from versions: )
Cleaning up...
No matching distribution found for python-mcrypt==1.1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for python-mcrypt==1.1
```

We will need to ask the python-mcrypt or pynsca developers how to resolve this. It seems the PyPi package is not setup correctly.
